apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache-api
  template:
    spec:
      containers:
      - name: cache-api
        image: k3d-cache-api.registry.localhost:12345/ahmedalhulaibi/cache-api:latest