apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache-api
  template:
    spec:
      containers:
      - name: cache-api
        image: k3d-cache-api.registry.localhost:12345/ahmedalhulaibi/cache-api:latest
        securityContext:
          capabilities:
            add:
              - SYS_PTRACE
        ports:
        - containerPort: 8080
        - containerPort: 8090
        - containerPort: 2345
---
apiVersion: v1
kind: Service
metadata:
  name: cache-api-svc
spec:
  type: ClusterIP
  ports:
  - name: debug
    targetPort: 2345
    port: 2345
    protocol: TCP
  selector:
    app: cache-api